# Generated by Django 6.0.1 on 2026-02-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline_execution', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pipelinejob',
            new_name='pipeline_ex_clerk_u_8ac1fa_idx',
            old_name='pipeline_ex_clerk_u_a4f0c0_idx',
        ),
        migrations.RenameIndex(
            model_name='pipelinejob',
            new_name='pipeline_ex_status_8d60c0_idx',
            old_name='pipeline_ex_status__2a4a67_idx',
        ),
    ]
