# Generated by Django 6.0.1 on 2026-02-12 09:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clerk_user_id', models.CharField(db_index=True, max_length=255)),
                ('original_file', models.FileField(upload_to='temp/originals/')),
                ('processed_file', models.FileField(blank=True, null=True, upload_to='temp/processed/')),
                ('selected_sheet', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clerk_user_id', 'created_at'], name='file_manage_clerk_u_a8519f_idx'), models.Index(fields=['status', 'expires_at'], name='file_manage_status_c72f67_idx')],
            },
        ),
    ]
